version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "reactive-kafka-topic:3:1"
      
  cassandra:
    image: cassandra:4.0
    container_name: 'cassandra'
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      CASSANDRA_SEEDS: cassandra
      CASSANDRA_PASSWORD_SEEDER: "yes"
      CASSANDRA_PASSWORD: cassandra
volumes:
  cassandra_data:
    driver: local
